# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: 'linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - script: |
      yarn install
      yarn run test
    displayName: 'yarn install and test'
- job: 'macOS'
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - script: |
      yarn install
      yarn run test
    displayName: 'yarn install and test'
- job: 'windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - script: |
      yarn install
      yarn run test
    displayName: 'yarn install and test'
